import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ArticleMarkdown } from "../src/components/article-markdown";
import { parseArticleMarkdown, isSafeImageUrl } from "../src/lib/article-markdown";
import { canonicalizeArticleLinks, resolveInternalArticleLink, validateInternalArticleLinks } from "../src/lib/article-link-policy";
import { directoryArticleName } from "../src/lib/airline-directory";
import { matchOpenFlightsAirlines } from "../src/lib/openflights";
import { InMemorySearchProvider } from "../src/lib/search-core";
import type { SearchDocument } from "../src/lib/search-types";

assert.equal(directoryArticleName("KLM"), "KLM Royal Dutch Airlines");
assert.equal(directoryArticleName("easyJet"), "easyJet");
const csv = '1,"easyJet",\\N,"U2","EZY","EASY","United Kingdom","Y"\n2,"United Feeder Service",\\N,"U2","UFS","FEEDER","United States","N"';
assert.equal(matchOpenFlightsAirlines(csv, [{ iata: "U2", icao: "EZY" }]).get("U2")?.name, "easyJet");
assert.equal(matchOpenFlightsAirlines(csv, [{ iata: "U2" }]).size, 0);
assert.equal(matchOpenFlightsAirlines(`${csv}\n${csv.split("\n")[0]}`, [{ iata: "U2", icao: "EZY" }]).size, 0);
const paths = new Set(["/commercial/british-airways", "/commercial/british-airways-fleet", "/airports/heathrow"]);
assert.equal(resolveInternalArticleLink("/airline/british-airways#fleet", paths), "/commercial/british-airways#fleet");
assert.equal(resolveInternalArticleLink("/aircraft/british-airways-fleet", paths), "/commercial/british-airways-fleet");
assert.equal(resolveInternalArticleLink("https://outside.test/airline/british-airways", paths), undefined);
assert.equal(resolveInternalArticleLink("/engines/missing", paths), null);
const parsed = parseArticleMarkdown("[BA](/airlines/british-airways) [Missing](/engines/missing)");
assert.equal(validateInternalArticleLinks(parsed.root, paths).length, 2);
const rendered = renderToStaticMarkup(<ArticleMarkdown root={canonicalizeArticleLinks(parsed.root, paths)} />);
assert.match(rendered, /href="\/commercial\/british-airways"/);
assert.doesNotMatch(rendered, /href="\/engines\/missing"/);
assert.match(rendered, /Missing/);
assert.equal(parsed.root.children[0].children?.[0].url, "/airlines/british-airways", "rendering leaves stored content intact");
const table = renderToStaticMarkup(<ArticleMarkdown root={parseArticleMarkdown("| Aircraft | Count |\n| --- | --- |\n| A350 | 12 |").root} />);
assert.equal((table.match(/<th scope="col"/g) || []).length, 2);
assert.match(table, /<thead>/);
assert.match(table, /<tbody><tr/);
for (const value of ["https://evil.test/a.png", "//upload.wikimedia.org/a.png", "/\\evil.test/a", "https://upload.wikimedia.org:444/a.png", "https://upload.wikimedia.org.evil.test/a.png"]) assert.equal(isSafeImageUrl(value), false, value);
for (const value of ["/image.png", "https://upload.wikimedia.org/a.png", "https://cdn.jetphotos.com/a.jpg"]) assert.equal(isSafeImageUrl(value), true, value);
assert.ok(parseArticleMarkdown("![Bad](https://evil.test/a.png)").errors.length);
assert.ok(parseArticleMarkdown("![Bad][photo]\n\n[photo]: https://evil.test/a.png").errors.length);
const base: SearchDocument = { id: "one", title: "British Airways", slug: "british-airways", contentType: "airline", href: "/commercial/british-airways", description: "", countries: ["United Kingdom"], terms: [{ kind: "title", value: "British Airways" }] };
const provider = new InMemorySearchProvider([base, { ...base, id: "two", countries: ["f![gb] United Kingdom"] }]);
assert.equal(provider.search({ query: "British", country: "United Kingdom" }).total, 2);
assert.deepEqual(provider.search({ query: "British" }).countries, ["United Kingdom"]);
console.log("Frontend audit regression tests passed");
